### PR TITLE
Adopted shell scripts to ant build.xml

### PR DESCRIPTION
**Pull request by isaiah**
Example output for exercise `01_Greetings`:

```log
Buildfile: ~jdk9-jigsaw/session-1-jigsaw-intro/01_Greetings/build.xml                                                           
                                                                                                                                                  
init:

prepare:

compile:

init:

run-tree:
     [echo] *** Displaying the contents of the 'src' folder ***                                                                                   
     [exec] src                                                                                                                                   
     [exec] └── src/com.greetings                                                                                                                 
     [exec]     ├── src/com.greetings/com                                                                                                         
     [exec]     │   └── src/com.greetings/com/greetings                                                                                           
     [exec]     │       └── src/com.greetings/com/greetings/Main.java                                                                             
     [exec]     └── src/com.greetings/module-info.java                                                                                            
     [exec]                                                                                                                                       
     [exec] 3 directories, 2 files                                                                                                                
     [echo] *** Compiling modules in 'mods/com.greetings' ***                                                                                     
    [javac] Compiling 2 source files to /home/isaiah/codes/jdk9-jigsaw/session-1-jigsaw-intro/01_Greetings/mods                                   
     [echo] *** Finished compiling modules into the 'mods/com.greetings' folder ***                                                               
                                                                                                                                                  
init:

run-tree:
     [echo] *** Displaying the contents of the 'mods' folder ***                                                                                  
     [exec] mods                                                                                                                                  
     [exec] ├── mods/com                                                                                                                          
     [exec] │   └── mods/com/greetings                                                                                                            
     [exec] │       └── mods/com/greetings/Main.class                                                                                             
     [exec] └── mods/module-info.class                                                                                                            
     [exec]                                                                                                                                       
     [exec] 2 directories, 2 files                                                                                                                
                                                                                                                                                  
run:                                                                                                                                              
     [echo] *** Running 'com.greetings.Main' inside the 'mods' folder.                                                                            
     [java] Greetings!                                                                                                                            
                                                                                                                                                  
BUILD SUCCESSFUL
Total time: 0 seconds
```

### CODE REVIEW

**Comment by neomatrix369** [comment]
Which platforms have you tested this one?

**Comment by isaiah** [comment]
Which build output do you mean, is there any example that I can follow?

**Comment by neomatrix369** [comment]
Build selective exercises using the ant command and copy the bottom part of the build results and paste here, for e.g. see https://github.com/AdoptOpenJDK/jdk9-jigsaw/pull/43#issuecomment-296377531

**Comment by isaiah** [comment]
Updated.

**Comment by neomatrix369** [comment]
Would be best to watch for changes and keep the `ant-version` branch in sync with `master`

**Comment by isaiah** [comment]
I can keep my fork up to date, but i'll need write access for your repo :)

**Comment by neomatrix369** [comment]
Regular PRs should be sufficient to keep the branch up-to-date

**Pull request merged**
