### PR TITLE
Added OS check

### PR DESCRIPTION
**Pull request by ioagentsmith**
02_JMod run fix

### CODE REVIEW

**Comment by kwahsog** [comment]
Tested and working now for Windows10.

**Comment by neomatrix369** [comment]
@kwahsog merge conflict, due to merging other PRs - sorry about it

**Comment by neomatrix369** [comment]
@kwahsog Still conflicting.

**Comment by ioagentsmith** [comment]
@kwahsog fixed

**Comment by neomatrix369** [comment]
@kwahsog Can I please ask you to paste the output of the script, before I merge it, just for posterity reasons. Thanks

**Comment by ioagentsmith** [comment]
@kwahsog : just  ran below:

christoff.smith@ChristoffS-PC MINGW64 /c/projects/jdk9-jigsaw/session-2-jlink/01_JLink (jdk9-jigsaw-fix-2)
$ ./link.sh

 *** Removing any existing greetings.jmod ***


 *** Creating a module (greetings.jmod) from multiple modules / packages / classes with jlink. ***

 *** Enlisting the contents of the module (greetings.jmod) ***
classes/module-info.class
classes/com/greetings/Main.class
classes/org/astro/World.class
 *** Currently JMOD files can be used at compile time and link time, but not at run time. ***
 *** Read further about JMod files at http://openjdk.java.net/jeps/261#Packaging:-JMOD-files ***

**Comment by ioagentsmith** [comment]
I see master has been fixed. Closing

**Pull request closed without merging**
