### PR TITLE
Fixed Java Home issue: Set Windows System variable JAVA_HOME to e.g. …

### PR DESCRIPTION
**Pull request by ioagentsmith**
…C:\libs\Java\jdk-9 without \lib at the end

### CODE REVIEW

**Comment by neomatrix369** [comment]
@ioagentsmith can you please paste the output of running this script in the section below

**Comment by ioagentsmith** [comment]
@neomatrix369 

export JAVA_HOME=/c/libs/Java/jdk-9/lib


$ ./link.sh

 *** Removing any existing executable directories ***

 *** Create an executable version of the com.greetings module ***
Error: Module java.base not found, required by com.greetings

**Comment by neomatrix369** [comment]
`Error: Module java.base not found, required by com.greetings` why is this failing the exercise does work on other platform, were you having this issue earlier as well?

**Comment by ioagentsmith** [comment]
@neomatrix369 this was the only exercise that had the issue. Some readme somewhere on today's docs said to set Java path incorrectly which I did

**Comment by neomatrix369** [comment]
I just want to make sure the new users of this exercise don't get an error, otherwise we will have to come back again and try to fix it.

**Comment by ioagentsmith** [comment]
there was nothing wrong with the example. the crux is the users setting the right JAVA_HOME system variable. we can reject this pull request

**Pull request closed without merging**
