### PR TITLE
Create getJDK.sh to download the non-Jigsaw JDK 9

### PR DESCRIPTION
**Pull request by lasombra**
This should fix issue #66

### CODE REVIEW

**Comment by neomatrix369** [comment]
@lasombra Works on Ubuntu - good to merge, can I request a new PR where you extract out the common parts in both `getJDK.sh` and `getJigsawJDK.sh` and put them in a common script, source that common script in both `getJDK.sh` and `getJigsawJDK.sh`, this will help remove some duplicated code and make it also easier to understand both scripts - thanks.

**Comment by neomatrix369** [comment]
@lasombra Can you also confirm if this has been tested on both MacOSX and Linux distros on your end?

**Comment by neomatrix369** [comment]
@lasombra Could you please reply to my prior comment and then we can proceed with this PR towards merging and closing.

**Comment by lasombra** [comment]
@neomatrix369 I'm sorry, completely missed it. I rested on Mac OS X and a RHEL server.

**Comment by neomatrix369** [comment]
Thats great

**Comment by neomatrix369** [comment]
No worries @lasombra I have merged it, closed the issues and also created a new enhancement issue  #69, in case it peeks your interest I'll assign it to you

**Pull request merged**
