### PR TITLE
Fixes issue #69

### PR DESCRIPTION
**Pull request by lasombra**
Refactoring get JDK bash scripts

### CODE REVIEW

**Comment by lasombra** [comment]
Sorry for the delay @neomatrix369. It took me longer than expected.

**Comment by neomatrix369** [comment]
It's a good starting point, I was thining something like this:
- `getJDK()` calls `commonJDK.sh` with parameters that are specific to downloading the JDK 9 EA
- `getJigsawJDK()` calls `commonJDK.sh` with parameters that are specific to downloading the JDK Jigsaw EA

This will push the remaining logic into `commonJDK.sh` and make the `getXxxxx.sh` more specific in functionality - what do you think?

**Comment by lasombra** [comment]
@neomatrix369 I think it can increase complexity a bit without a real gain.

**Comment by neomatrix369** [comment]
There's a number of duplicates in the `getXxxx.sh` scripts that could be moved into the common script.

**Comment by neomatrix369** [comment]
@lasombra I'll merge this for now and have a revisit to see if any polishing is needed in any of the new scripts - thanks for your efforts again

**Comment by lasombra** [comment]
@neomatrix369 No problem. Sorry I couldn't do more. I'll try to tackle this when things calm down a bit.

**Pull request merged**
