### PR TITLE
Convert shell scripts to ant build.xml

### PR DESCRIPTION
**Pull request by isaiah**
Some of the commands has to use the `exec` task, as there is no equivalent native ant task.

### CODE REVIEW

**Comment by neomatrix369** [comment]
@isaiah Thanks for this contribution - do you mind creating a new branch and creating your PR against it, let's preserve the bash scripts for the exercises, please.

Maybe call the branch `ant-version` just like we have a branch for `maven` (https://github.com/AdoptOpenJDK/jdk9-jigsaw/tree/maven-version).

**Comment by neomatrix369** [comment]
You didn;t need to close the PR but thats fine now

**Comment by isaiah** [comment]
@neomatrix369 Do you have to create the branch in the repo so I can create another PR against? I can only PR against the existing branches.

**Comment by neomatrix369** [comment]
Let me create a branch from you and you can then PR against it

**Comment by neomatrix369** [comment]
@isaiah - here you go https://github.com/AdoptOpenJDK/jdk9-jigsaw/tree/ant-version

**Comment by isaiah** [comment]
Recreated https://github.com/AdoptOpenJDK/jdk9-jigsaw/pull/74

**Pull request closed without merging**
