### PR TITLE
Change the behavior of ConcurrentHashMap ever so slightly without breaking anything

### PR DESCRIPTION
**Pull request by blalasaadri**
This example demonstrates, how a small, non-breaking change can be introduced via module patching. Thought honestly, a class other than `ConcurrentHashMap` (which is used so widely AND uses generics) may be a much better (= simpler) example.

### CODE REVIEW

**Comment by neomatrix369** [comment]
@blalasaadri Great one, I think this can be a separate exercise on its own, you want to submit is a `08_patch_module_option`

**Comment by blalasaadri** [comment]
I have adjusted the pull request to follow your suggestions; example 07 is now simplified so that it works but only overwrites the `toString` method. I then added a new example (also 07) which shows what more can be done by overwriting `containsKey(String)`. The READMEs for both examples have also been adjusted to reflect the current state.

**Comment by neomatrix369** [comment]
Totally agree about a class other than `ConcurrentHashMap` should be used but this one is a pretty interesting one too, no harm in having a difficult problem for everyone to hack on. Lots of learning comes out of it.

**Comment by neomatrix369** [comment]
Before you merge could you please post the output of all the scripts that your ran for both exercises 07 and 08. Thanks.

**Comment by neomatrix369** [comment]
Is this file name correct `works-with-jdk-9-ea-166` - did you run on Build 166? Otherwise please rename it to another name

**Comment by neomatrix369** [comment]
@blalasaadri any chance to look at this PR so we can merge it asap

**Comment by blalasaadri** [comment]
Good catch about the `works-with-jdk-9-ea-166` file; I actually used build 165, so I've modified that. I'll add the outputs of those scripts as comments here; if you need them as part of the README or something, I can add those too of course.

Output of `07_patch_module_option/compile.sh`:
```

 *** Displaying the contents of the 'src' folder *** 
src
├── src/com.greetings
│   ├── src/com.greetings/com
│   │   └── src/com.greetings/com/greetings
│   │       └── src/com.greetings/com/greetings/Main.java
│   └── src/com.greetings/module-info.java
└── src/java.base
    └── src/java.base/java
        └── src/java.base/java/util
            └── src/java.base/java/util/concurrent
                └── src/java.base/java/util/concurrent/ConcurrentHashMap.java

7 directories, 3 files

 *** Compiling a new version of ConcurrentHashMap *** 

 *** Compiling Main class*** 

 *** Displaying the contents in the 'mypatches/java.base' folder *** 
mypatches/java.base
└── mypatches/java.base/java
    └── mypatches/java.base/java/util
        └── mypatches/java.base/java/util/concurrent
            └── mypatches/java.base/java/util/concurrent/ConcurrentHashMap.class

3 directories, 1 file

 *** Displaying the contents in the 'mods/com.greetings' folder *** 
mods/com.greetings
├── mods/com.greetings/com
│   └── mods/com.greetings/com/greetings
│       └── mods/com.greetings/com/greetings/Main.class
└── mods/com.greetings/module-info.class

2 directories, 2 files
```
Output of `07_patch_module_option/run.sh`:
```

 *** Running without the patch from within the mods folder. *** 

Hello {1=one, 2=two, 3=three}

 *** Running with the patch from within the mods folder. *** 

Hello patched ConcurrentHashMap {1=one, 2=two, 3=three}
```
Output of `07_patch_ConcurrentHashMap/compile.sh`:
```

 *** Displaying the contents of the 'src' folder *** 
src
├── src/com.greetings
│   ├── src/com.greetings/com
│   │   └── src/com.greetings/com/greetings
│   │       └── src/com.greetings/com/greetings/Main.java
│   └── src/com.greetings/module-info.java
└── src/java.base
    └── src/java.base/java
        └── src/java.base/java/util
            └── src/java.base/java/util/concurrent
                └── src/java.base/java/util/concurrent/ConcurrentHashMap.java

7 directories, 3 files

 *** Compiling a new version of ConcurrentHashMap *** 

 *** Compiling Main class*** 

 *** Displaying the contents in the 'mypatches/java.base' folder *** 
mypatches/java.base
└── mypatches/java.base/java
    └── mypatches/java.base/java/util
        └── mypatches/java.base/java/util/concurrent
            └── mypatches/java.base/java/util/concurrent/ConcurrentHashMap.class

3 directories, 1 file

 *** Displaying the contents in the 'mods/com.greetings' folder *** 
mods/com.greetings
├── mods/com.greetings/com
│   └── mods/com.greetings/com/greetings
│       └── mods/com.greetings/com/greetings/Main.class
└── mods/com.greetings/module-info.class

2 directories, 2 files
```
Output of `07_patch_ConcurrentHashMap/run.sh`:
```

 *** Running without the patch from within the mods folder. *** 

Hello {one=1, two=2, three=3}
Is Duke home? false

 *** Running with the patch from within the mods folder. *** 

Hello patched ConcurrentHashMap {one=1, two=2, three=3} + Duke
Is Duke home? true
```

**Comment by neomatrix369** [comment]
@blalasaadri merging, any other cosmetic changes I'll decorate it later on

**Comment by neomatrix369** [comment]
Thanks again for this PR - really adds value

**Pull request merged**
